<html>
<body>
Reports any calls to <code>Throwable.initCause()</code> where the exception constructor also takes a <code>Throwable</code> cause argument.
In this case, the <code>initCause()</code> call can be removed and its argument added to the call to the exception's constructor.
<p>Example:</p>
<pre>
  try {
      process();
  }
  catch (RuntimeException ex) {
    RuntimeException wrapper = new RuntimeException("Error while processing");
    wrapper.initCause(ex); // Unnecessary call to 'Throwable.initCause()'
    throw wrapper;
  }
</pre>
<p>A quick-fix is provided to pass the cause to constructor:</p>
<pre>
  try {
      process();
  }
  catch (RuntimeException ex) {
    RuntimeException wrapper = new RuntimeException("Error while processing", ex);
    throw wrapper;
  }
</pre>
<!-- tooltip end -->
<p>
<small>New in 2016.1</small>
</body>
</html>